import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const poppins = Poppins({
    weight: ["200", "400", "600", "800"], 
    subsets: ["latin"],
    variable: "--font-poppins",
});

const bauhausStdMedium = localFont({
    src: "../assets/fonts/BauhausStdMedium.otf",
    display: "swap",
    weight: "600",
    variable: "--font-bauhaus-std-medium",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${bauhausStdMedium.variable}`}>{children}</body>
    </html>
  );
}
